import Emittery from 'emittery';

// 创建全局事件发射器
export const EventEmitter = new Emittery();

// 定义事件名称常量
export const EVENT_NAMES = {
  SEND_MESSAGE: 'SEND_MESSAGE',
  MESSAGE_COMPLETE: 'MESSAGE_COMPLETE',
  CLEAR_MESSAGES: 'CLEAR_MESSAGES',
  ADD_NEW_TOPIC: 'ADD_NEW_TOPIC',
  TOPIC_CREATED: 'TOPIC_CREATED',
  SHOW_TOPIC_SIDEBAR: 'SHOW_TOPIC_SIDEBAR',
  FORCE_TOPIC_LIST_UPDATE: 'FORCE_TOPIC_LIST_UPDATE',
  FORCE_MESSAGES_UPDATE: 'FORCE_MESSAGES_UPDATE'
}; 